version: '3.8'

services:
  db:
    build:
      context: ./mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - netms
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  mslogistica:
    build:
      context: ./mslogistica
    container_name: mslogistica
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      DB_URL: mysql_db
      DB_NAME: logistica
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - netms

  msprodutos:
    build:
      context: ./msprodutos
    container_name: msprodutos
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      DB_URL: mysql_db
      DB_NAME: produtos
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - netms

  msclientes:
    build:
      context: ./msclientes
    container_name: msclientes
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      DB_URL: mysql_db
      DB_NAME: clientes
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - netms

  mspedidos:
    build:
      context: ./mspedidos
    container_name: mspedidos
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      PRODUTOS_URL: msprodutos
      DB_URL: mysql_db
      DB_NAME: pedidos
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - netms

  mscargaprodutos:
    build:
      context: ./mscargaprodutos
    container_name: mscargaprodutos
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      PRODUTOS_URL: msprodutos
      DB_URL: mysql_db
      DB_NAME: cargaproduto
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - netms

  msgateway:
    build:
      context: ./gateway
    container_name: msgateway
    ports:
      - "8080:8080"
    networks:
      - netms

networks:
  netms:
    driver: bridge
