version: '3.8'

services:
  db:
    build:
      context: ./mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - netpedidos

  mslogistica:
    build:
      context: ./mslogistica
    container_name: mslogistica
    depends_on:
      - db
    ports:
      - "8085:8085"
    environment:
      DB_URL: jdbc:mysql://db:3307/logistica
      DB_NAME: logistica
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - netpedidos

networks:
  netpedidos:
    driver: bridge